version: '3.4'

services:
  bot:
    image: ib.ai
    restart: on-failure:3
    build: ./docker
    volumes:
      - ./docker/Config.toml:/opt/IB.ai/Config.toml
    depends_on:
      - mongo
      - mongo-express

  mongo:
    image: mongo
    restart: always
    depends_on:
      - mongo-express

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081